security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: login

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: /api/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

  access_control:
    # Auth
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/test, roles: PUBLIC_ACCESS }

    # Session join + infos
    - { path: ^/api/session/[A-Z0-9]+/games, roles: PUBLIC_ACCESS }
    - { path: ^/api/session/[A-Z0-9]+/join, roles: PUBLIC_ACCESS }
    - { path: ^/api/session/.*/join, roles: PUBLIC_ACCESS }
    - { path: ^/api/session/[A-Z0-9]+$, roles: PUBLIC_ACCESS, methods: [GET] }

    # Jeux publics
    - { path: ^/api/association, roles: PUBLIC_ACCESS }
    - { path: ^/api/crossword, roles: PUBLIC_ACCESS }
    - { path: ^/api/formulation, roles: PUBLIC_ACCESS }
    - { path: ^/api/participation, roles: PUBLIC_ACCESS }

    # Admin
    - { path: ^/api/stats/dashboard, roles: ROLE_ADMIN }
    - { path: ^/api/sessions, roles: ROLE_ADMIN }

    # Tout le reste nécessite authentification
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 1030
